### ISSUE TITLE
Q&A and bugs

### ISSUE THREAD

**Issue by nafanz** [kubow/vcf_editor#3]
[2024-11-26 14-47-10.webm](https://github.com/user-attachments/assets/4557f928-ed3a-4eec-bb25-4bbadf24947d)

The application is running and the contacts file is loaded, if you **don't select** a contact from the list and try to move (<>) there will be an error.

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.12/tkinter/__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/qa/vcf_editor/main.py", line 156, in prev
    self.control()
  File "/home/qa/vcf_editor/main.py", line 165, in control
    if self.contacts_list.curselection()[0] + 1 >= len(self.contacts_lib.dic):
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: tuple index out of range
```

Since in this case `self.contacts_list.curselection()` is empty, you can add a check that the tuple is not empty.

```
if len(self.contacts_list.curselection()) != 0 and self.contacts_list.curselection()[0] + 1 >= len(self.contacts_lib.dic):
    return
```

But it's probably more correct to disable the button if no contact is selected from the list.

After that I encounter another error, but I still don't understand how to work with `self.form`.

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.12/tkinter/__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/qa/vcf_editor/main.py", line 162, in next
    self.control()
  File "/home/qa/vcf_editor/main.py", line 169, in control
    self.form['f1_inp'].delete(0, 'end')
    ~~~~~~~~~^^^^^^^^^^
KeyError: 'f1_inp'
```

I would be grateful if you could clarify a little the logic of the `control` function and how it works with the `form`.

**Comment by kubow** [comment]
Hey @nafanz, that's my bad. I wrote this code some time ago and was not skilled enough to deal with the unification of field naming. 
Anyway, I looked into that and I believe it now lists properly.
The `control` method now only focuses on the proper fields building.

I touched a bit main class structure (still far away from optimized code) and you have now visually divided components (for tkinter-related objects on the screen and active/loaded list of contacts) as you can debug easier.

![image](https://github.com/user-attachments/assets/5299519f-c27a-41aa-b2db-9b3ebc269bab)
Let me know if works!

**Comment by nafanz** [comment]
@kubow 
Yes, now the problems described above have been resolved. Thanks for fixing it. At the moment, the logic of working with the graphical interface is something incomprehensible to me; I wouldn’t have been able to handle it myself.

I would suggest not closing this discussion for now, so that there is room for discussing other issues. So as not to create new discussions. You could rename this to Q&A or something similar.

For example, I don't understand the logic of opening a `Directory` where only one line is read from a file and there is no possibility of further navigation through it. What is this for?

**Comment by nafanz** [comment]
* Select the `Directory` menu, the first contact in the file will be displayed
* Select it and edit any field
* Click `Save`

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.12/tkinter/__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/qa/vcf_editor/main.py", line 191, in save
    self.build_contact()
  File "/home/qa/vcf_editor/main.py", line 205, in build_contact
    v = Contact.vcf_object(name, family, phone, path)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qa/vcf_editor/Contact.py", line 112, in vcf_object
    m = open_vcf(loc)
        ^^^^^^^^^^^^^
  File "/home/qa/vcf_editor/Contact.py", line 102, in open_vcf
    with open(location, mode='r', encoding='utf-8') as vcf_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/qa/experiments/МТС.vcf'
```

Crashes when calling the `vcf_object` function, which in turn calls `open_vcf` and tries to open a file that does not exist.

I have two questions here:
* Are we sure we want to include the variable `n` in `path`? That is, create a new file that will be named like the contact from the list or should we still update the existing file (which we initially downloaded)?
```
    def build_contact(self):
        if self.active['contact']['N'].family:
            n = self.active['contact']['N'].given + ' ' + self.active['contact']['N'].family
        else:
            n = self.active['contact']['FN']
        path = f'{self.active["location"]}/{n}.vcf'
```
* What is the purpose of calling `open_vcf`? If we want to open a new file, then we haven't created it yet. If it's an old one, then we're already working with it.

**Comment by nafanz** [comment]
@kubow 
After the last edits I encountered a problem with opening my file:

```
Error loading file /home/qa/experiments/Контакты.vcf: sequence item 0: expected str instance, list found
```

It occurs in the `parse_vcard` function when processing `adr` if the address contains a comma (e.g. `Октябрьская 1, кв. 2`)
Because of this, it treats the string as a list.

Demo fragment (Sensitive data excluded):

```
BEGIN:VCARD
VERSION:2.1
N;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:=D0=98=D0=B2=D0=B0=D0=BD=D0=BE=D0=B2;=D0=98=D0=B2=D0=B0=D0=BD;;;
FN;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:=D0=98=D0=B2=D0=B0=D0=BD=20=D0=98=D0=B2=D0=B0=D0=BD=D0=BE=D0=B2
TEL;CELL:+79049742111
X-SAMSUNGADR;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:;;=D0=9B=D0=B5=D0=BD=D0=B8=D0=BD=D0=B0=20=31=2F=32=20=D0=BA=D0=B2=2E=20=
=31=32=33;;;;;=D0=9B=D0=B5=D0=BD=D0=B8=D0=BD=D0=B0=20=31=2F=32=20=D0=BA=D0=B2=2E=20=
=31=32=33
ADR;HOME;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:;;=D0=9B=D0=B5=D0=BD=D0=B8=D0=BD=D0=B0=20=31=2F=32=20=D0=BA=D0=B2=2E=20=
=31=32=33;;;;
X-SAMSUNGADR;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:;;=D0=9E=D0=BA=D1=82=D1=8F=D0=B1=D1=80=D1=8C=D1=81=D0=BA=D0=B0=D1=8F=20=
=31=2C=20=D0=BA=D0=B2=2E=20=32;;;;;=D0=9E=D0=BA=D1=82=D1=8F=D0=B1=D1=80=D1=8C=D1=81=D0=BA=D0=B0=D1=8F=20=
=31=2C=20=D0=BA=D0=B2=2E=20=32
ADR;WORK;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:;;=D0=9E=D0=BA=D1=82=D1=8F=D0=B1=D1=80=D1=8C=D1=81=D0=BA=D0=B0=D1=8F=20=
=31=2C=20=D0=BA=D0=B2=2E=20=32;;;;
END:VCARD
```

Debugging:

```
<VCARD| [<VERSION{}2.1>, <ADR{'CHARSET': ['UTF-8']}Ленина 1/2 кв. 123
,  >, <ADR{'CHARSET': ['UTF-8']}Октябрьская 1
 кв. 2
,  >, <FN{'CHARSET': ['UTF-8']}Иван Иванов>, <N{'CHARSET': ['UTF-8']} Иван  Иванов >, <TEL{}+79049742111>, <X-SAMSUNGADR{'CHARSET': ['UTF-8']};;Ленина 1/2 кв. 123;;;;;Ленина 1/2 кв. 123>, <X-SAMSUNGADR{'CHARSET': ['UTF-8']};;Октябрьская 1>]>
```

Probably it can be solved like this, I provided the full fragment on [stackoverflow](https://ru.stackoverflow.com/a/1599983/401599)

```
for address in contact.adr_list:
                street = address.value.street
                if isinstance(street, str):
                    print(street)
                else:
                    print(''.join(street))
```

But I haven't figured out yet how to integrate it into the existing code.

**Comment by kubow** [comment]
Hi @nafanz, you are right there are multiple concepts, that do not make much sense in the overall ease of use (caused by my lack of knowledge at the time of creation).

I had to rewrite some functions and extract them as it makes then much more sense where to step in if needed.
[Here](https://mermaid.live/edit#pako:eNp1k0Fv2zAMhf-KoNO6Nund2KVYO2BAu8OW0xDAoC061iKLBkUVy7r897FpExiy54NhfY-inp7kF9uSQ1vZNkBK9x52DMM2Gn0G8HG12ZtPf1crYz5TFGjl0SdZkEfghPVzC-wW1JYRZEmuzLXzrRht7J9xUWrf1k118E1ZsNl_NE0WoXjbEQ-3Qc2l9Xpd1jXZB1d3HoNLH66W1fd15jJjx5j6uUCxThhwac5rM6ZwFk7ZThN8eePGXPv4usUcBfnCTvvWlzEXBOOI0Z37KcDfI7FMAGmBJtxNUCBwtfOsFokPZ-E49TQ5t4snnZmETZdDqCMMWPCdnlRcEjoYfDiUCjCbsaeIdcxDg5wKDTW1UEJwTjNPmIoliHcQ_R8QT7GQflFTi5dQumo8S-_gUOBIMu3OKJnjYkTTyzvN6ATMl28zNCebh8cZe3i6-zqnd_ff_2tKb4O9sQOyJub0jz2Z2VrpUQO3lX464P3WbuNR6yAL_TjE1lbCGW8sU971tuogJB3l0emm3n_3Cx0h_iQ6j4__AH6XQk0) is a simple scheme, that describes how it goes under the hood (with the latest commit I made a while ago).

- `parse_vcard()` takes care about parsing vcf files to a dictionary (to store it either in `ContactList` class as `dic` property or tkinter widgets)
- `create_vcard()` then handles creation of vcard object from that dictionary
- for the address problem, it is actually common across more fields they can be either string or an array - I tried to take case about that

Let me know if this makes more sense now. There might be still some issues around (as I do not have any real testing VCF around). Feel flee also to suggest any other improvement.
I am thinking for the future - I will involve multiple VCF files and add testing, to have the functionality more robust...

**Comment by nafanz** [comment]
@kubow 
Unfortunately, nothing has changed. As far as I can tell, the added function `create_vcard` is called only in `export` and `build_contact`, it is not used in the scenario I described.

I will try to add a test file of Russian-language contacts version 2.1 in the near future.

**Comment by kubow** [comment]
Hey @nafanz , thank you for submitting the test file, I have solved that a bit [differently](https://github.com/kubow/vcf_editor/commit/8ce16e8d208b6cd7a36c1bf3b16b616976ab9b42), however I can see there many potential issues once reconstructing the vcf back, I will try to address that once I have some spare time.

**Comment by nafanz** [comment]
@kubow 
Thank you, now there is no error when opening the file.

I sent a small PR and wrote there a problem with curly brackets in the display of the address.
